- name: Install necessary packages
  ansible.builtin.package:
    name: ca-certificate
    state: present

- name: Create keyrings directory
  ansible.builtin.file:
    src: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download APT repository GPG key
  ansible.builtin.get_url:
    url: 'https://download.docker.com/linux/{{ ansible_facts["distribution"] | lower }}/gpg'
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add APT repository
  ansible.builtin.deb822_repository:
    types: deb
    uris: 'https://download.docker.com/linux/{{ ansible_facts["distribution"] | lower }}'
    suites: '{{ ansible_facts["distribution_release"] | lower }}'
    components: stable
    signed_by: /etc/apt/keyrings/docker.asc
