---
driver:
  name: podman

platforms:
  - name: alpine
    image: docker.io/python:alpine

provisioner:
  env:
    ANSIBLE_COLLECTIONS_PATH: ${MOLECULE_PROJECT_DIRECTORY}/../../../../../ansible_collections
