chrony_orchestrator_servers: '{{ groups | dict2items | rejectattr("key", "in", [ "all" ]) | selectattr("key", "in", chrony_orchestrator_server_groups) | items2dict }}'
chrony_orchestrator_clients: '{{ groups | dict2items | rejectattr("key", "in", [ "all" ]) | selectattr("key", "in", chrony_orchestrator_client_groups) | items2dict }}'
chrony_orchestrator_sservers: '{{ chrony_orchestrator_servers | dict2items | subelements("value") | map(attribute=1) }}'
chrony_orchestrator_cservers: '{{ chrony_orchestrator_servers | dict2items | subelements("value") | map(attribute=1) }}'
