docker_packages: |
  {{ 
    [ "docker-ce", "docker-ce-cli", "docker-compose-plugin" ]
    | zip_longest([ ], fillvalue=docker_version)
    | map("join", "=")
    + [ "containerd.io", "docker-buildx-plugin" ]
  }}
