- name: Perform common actions
  become: true
  hosts: all
  roles:
    - role: tesselate.ceph.ceph_common

- name: Bootstrap Ceph cluster
  become: true
  hosts: mgr
  roles:
    - role: tesselate.ceph.ceph_bootstrap
      run_once: true
